### ISSUE TITLE
Last step facturation

### ISSUE THREAD

**Issue by Adwind** [316k/tp-maintenance#1]
When the user entered everything and the message is send everything is okay, but it crash before receiving an answer from the bank.

**Comment by DrPyser** [comment]
j'ai règlé le problème en modifiant la classe "BanqueSimulee" pour quelle buisse gérer le paiment de facture. Ça fait juste retirer l'argent du compte, par contre. JE sais pas si y'a autre chose à faire.

**Comment by Adwind** [comment]
Oh mon dieu que j'ai fail, merci pour tes yeux :+1:
